### PR TITLE
ci: Add MSRV test

### LINKED ISSUE #127: MSRV Policy & CI
It would be helpful to both set policy and CI to test the MSRV e.g. to maybe help issues like this:
- #126

### PR DESCRIPTION
**Pull request by pinkforest**
Assuming MSRV 1.65

Fixes #127 

Depends on fix for #126 re-based in

Failure as expected with 1.65: https://github.com/pinkforest/rust-id3/actions/runs/8002170702/job/21854841329
Where as current stable works ok.

### CODE REVIEW

**Comment by polyfloyd** [comment]
Not entirely sure why this fails. It might be something with unstable Rust?

Could you revert back the cache changes? I'd prefer to keep to GitHub's official solution for now

**Comment by pinkforest** [comment]
Yeah sure, it seems some transient dependency doesn't support MSRV but let me check that - the lib itself is fine all the way down 1.63 - the minimal versions is standard test
Also Swatinem's rust-cache is used all around the Rust ecosystem that has become "standard" - e.g. tokio https://github.com/tokio-rs/tokio/blob/master/.github/workflows/ci.yml#L111 but I'll remove it as wished but don't recommend hand-crafting manual cache as it has caused trouble elsewhere caching things it should not

**Comment by pinkforest** [comment]
All green now :sweat_smile: :partying_face: :tada:

**Comment by polyfloyd** [comment]
Excellent! Thanks!

**Pull request merged**
